//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebNangCao.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cam_nang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cam_nang()
        {
            this.Url_anh = new HashSet<Url_anh>();
        }
    
        public string ma_bai_viet { get; set; }
        public string ten_bai_viet { get; set; }
        public string chuyen_muc { get; set; }
        public string ma_dd { get; set; }
        public Nullable<int> luot_xem { get; set; }
        public Nullable<int> sl_thich_bai { get; set; }
        public Nullable<int> sl_share_bai { get; set; }
        public Nullable<System.DateTime> ngay_dang { get; set; }
        public string noi_dung { get; set; }
    
        public virtual Dia_diem Dia_diem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Url_anh> Url_anh { get; set; }
    }
}
