//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebNangCao.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ct_phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ct_phong()
        {
            this.Thanh_toan = new HashSet<Thanh_toan>();
            this.Url_anh = new HashSet<Url_anh>();
            this.Khach_hang = new HashSet<Khach_hang>();
            this.Tuy_chon = new HashSet<Tuy_chon>();
        }
    
        public string ma_ks { get; set; }
        public string ma_phong { get; set; }
        public string ma_loai_phong { get; set; }
        public string khuyen_mai_phong { get; set; }
        public string id_anh { get; set; }
    
        public virtual Khach_san Khach_san { get; set; }
        public virtual Loai_phong Loai_phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thanh_toan> Thanh_toan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Url_anh> Url_anh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Khach_hang> Khach_hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tuy_chon> Tuy_chon { get; set; }
    }
}
