//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebNangCao.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dia_diem_gan_ks
    {
        public string id_dia_diem { get; set; }
        public string ma_ks { get; set; }
        public string ten_dia_diem_gan_ks { get; set; }
        public Nullable<double> khoang_cach { get; set; }
    
        public virtual Khach_san Khach_san { get; set; }
    }
}
