//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebNangCao.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khach_san
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Khach_san()
        {
            this.Ct_phong = new HashSet<Ct_phong>();
            this.Dia_diem_gan_ks = new HashSet<Dia_diem_gan_ks>();
            this.Url_anh = new HashSet<Url_anh>();
            this.Tien_nghi = new HashSet<Tien_nghi>();
        }
    
        public string ma_ks { get; set; }
        public string ten_ks { get; set; }
        public string dia_chi { get; set; }
        public Nullable<double> diem_danh_gia { get; set; }
        public string ma_tinh { get; set; }
        public Nullable<int> sl_share { get; set; }
        public Nullable<int> sl_like { get; set; }
        public Nullable<int> sl_danh_gia { get; set; }
        public string gioi_thieu_ks { get; set; }
        public string chinh_sach_ks { get; set; }
        public string loai_ks { get; set; }
        public string id_anh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ct_phong> Ct_phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dia_diem_gan_ks> Dia_diem_gan_ks { get; set; }
        public virtual Tinh Tinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Url_anh> Url_anh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tien_nghi> Tien_nghi { get; set; }
    }
}
