//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebNangCao.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khach_hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Khach_hang()
        {
            this.Tours = new HashSet<Tour>();
            this.Ct_phong = new HashSet<Ct_phong>();
        }
    
        public string tai_khoan { get; set; }
        public string ten_kh { get; set; }
        public string mat_khau { get; set; }
        public string ma_quyen { get; set; }
        public string sdt_kh { get; set; }
        public string email { get; set; }
        public string dia_chi_kh { get; set; }
        public Nullable<int> diem_thuong { get; set; }
        public string ks_yeuthich { get; set; }
    
        public virtual Quyen_truy_cap Quyen_truy_cap { get; set; }
        public virtual Thanh_toan Thanh_toan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ct_phong> Ct_phong { get; set; }
    }
}
