//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebNangCao.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loai_phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loai_phong()
        {
            this.Ct_phong = new HashSet<Ct_phong>();
        }
    
        public string ma_loai_phong { get; set; }
        public string ten_loai_phong { get; set; }
        public Nullable<double> dien_tich { get; set; }
        public string mo_ta_phong { get; set; }
        public string tien_nghi_phong { get; set; }
        public Nullable<double> gia_phong { get; set; }
        public Nullable<int> so_giuong { get; set; }
        public Nullable<int> so_nguoi_max { get; set; }
        public Nullable<int> so_phong_con_lai { get; set; }
        public Nullable<int> tong_so_phong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ct_phong> Ct_phong { get; set; }
    }
}
